const orders = [
  {
    id: 1,
    orderId: "TX1001",
    type: "BUY",
    stock: "TCS",
    exchange: "NSE",
    qty: 10,
    price: 3560,
    status: "Completed",
    date: "09 Jul 2026",
    time: "10:15 AM",
  },

  {
    id: 2,
    orderId: "TX1002",
    type: "SELL",
    stock: "INFY",
    exchange: "NSE",
    qty: 5,
    price: 1720,
    status: "Pending",
    date: "09 Jul 2026",
    time: "11:40 AM",
  },

  {
    id: 3,
    orderId: "TX1003",
    type: "BUY",
    stock: "HDFC",
    exchange: "NSE",
    qty: 20,
    price: 1840,
    status: "Completed",
    date: "08 Jul 2026",
    time: "09:25 AM",
  },

  {
    id: 4,
    orderId: "TX1004",
    type: "BUY",
    stock: "RELIANCE",
    exchange: "NSE",
    qty: 8,
    price: 2890,
    status: "Cancelled",
    date: "08 Jul 2026",
    time: "02:10 PM",
  },

  {
    id: 5,
    orderId: "TX1005",
    type: "SELL",
    stock: "ICICIBANK",
    exchange: "NSE",
    qty: 15,
    price: 1185,
    status: "Completed",
    date: "07 Jul 2026",
    time: "12:35 PM",
  },

  {
    id: 6,
    orderId: "TX1006",
    type: "BUY",
    stock: "SBIN",
    exchange: "NSE",
    qty: 25,
    price: 910,
    status: "Pending",
    date: "07 Jul 2026",
    time: "03:05 PM",
  },

  {
    id: 7,
    orderId: "TX1007",
    type: "SELL",
    stock: "WIPRO",
    exchange: "NSE",
    qty: 12,
    price: 548,
    status: "Completed",
    date: "06 Jul 2026",
    time: "10:50 AM",
  },

  {
    id: 8,
    orderId: "TX1008",
    type: "BUY",
    stock: "LT",
    exchange: "NSE",
    qty: 6,
    price: 3725,
    status: "Pending",
    date: "06 Jul 2026",
    time: "01:20 PM",
  },

  {
    id: 9,
    orderId: "TX1009",
    type: "SELL",
    stock: "AXISBANK",
    exchange: "NSE",
    qty: 9,
    price: 1260,
    status: "Completed",
    date: "05 Jul 2026",
    time: "11:15 AM",
  },

  {
    id: 10,
    orderId: "TX1010",
    type: "BUY",
    stock: "HCLTECH",
    exchange: "NSE",
    qty: 18,
    price: 1625,
    status: "Completed",
    date: "05 Jul 2026",
    time: "04:10 PM",
  },
];

export default orders;